apiVersion: v1
kind: ConfigMap
metadata:
  name: kubelab-api-config
  namespace: kubelab
data:
  APP_ENV: "development"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "kubelab"
  POSTGRES_USER: "kubelab"
